version: '3.8'

volumes:
  redis:

networks:
  redis_net:
    name: redis_net
    driver: bridge

services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    networks:
      - redis_net
    ports:
      - 8081:8081
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379

  redis:
    image: redis:7.0.4
    container_name: redis
    networks:
    - redis_net
    volumes:
    - redis:/var/lib/redis
    ports:
    - 6379:6379
    environment:
      REDIS_PASSWORD: redispwd

